# Generated by Django 6.0.3 on 2026-03-08 00:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMFileArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dicom_zip_files/', validators=[django.core.validators.FileExtensionValidator(['zip'])])),
                ('archive_extracted', models.BooleanField(default=False)),
                ('archive_extraction_date_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DICOMSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=255, unique=True)),
                ('modality', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_of_reference_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('series_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DICOMStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_instance_uid', models.CharField(max_length=255, unique=True)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255, unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DICOMInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(max_length=255, unique=True)),
                ('instance_number', models.IntegerField(blank=True, null=True)),
                ('instance_file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dicomseries')),
            ],
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dicomstudy'),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.CreateModel(
            name='StapleROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dicominstance')),
            ],
        ),
        migrations.CreateModel(
            name='RTStructROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_number', models.IntegerField(blank=True, null=True)),
                ('roi_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dicominstance')),
                ('staple_roi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stapleroi')),
            ],
        ),
        migrations.CreateModel(
            name='StructureROIPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_calculated', models.CharField(blank=True, max_length=255, null=True)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reference_rt_structure_roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_structure_roi', to='app.rtstructroi')),
                ('target_rt_structure_roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_structure_roi', to='app.rtstructroi')),
            ],
        ),
    ]
