# Generated by Django 6.0.3 on 2026-03-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dicomseries_nifti_file_path'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rtstructroi',
            name='either_instance_or_staple_roi',
        ),
    ]
