# Generated by Django 6.0.3 on 2026-03-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_rtstructroi_either_instance_or_staple_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stapleroi',
            name='staple_roi_file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
